### ISSUE TITLE
Modal Problems

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/forge#553]
@namimody commented on [Fri Apr 29 2016](https://github.com/DoSomething/phoenix/issues/6400)
#### Current Behavior

Modal design seems to be off with the new updates to Forge -- see screenshot below. Quite a few modal exist on Birthday Mail, as one place you could take a look (https://www.dosomething.org/us/node/2461/active)
#### Desired Behavior

Leaving this for you to fill out @lkpttn!
#### Why This Matters

Tons of modals across the site, plus Birthday Mail is sponsored.
#### OS/Browser (optional)

Chrome
#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/12396076/14931428/51d6fcec-0e39-11e6-9ed1-d6d6ea532c9d.png)

cc @mikefantini

**Comment by lkpttn** [comment]
@DFurnes Didn't we fix this before? I think it's just a syntax error with the modals.

**Comment by DFurnes** [comment]
These are bugs with specific modals on Phoenix. Closing this and re-opening the original issue!
