### ISSUE TITLE
Add Snapchat + We Heart It to Forge Social Icon Pattern

### ISSUE THREAD

**Issue by namimody** [DoSomethingArchive/forge#557]
http://forge.dosomething.org/#social-icon

Snapchat SVG available from: https://icomoon.io/

We Heart It SVG: https://dosomething.slack.com/files/nami/F1JHXN3RC/weheartit-01.svg

**Comment by DFurnes** [comment]
It'd also be nice to update to the new Instagram icon while we're in here.

![screen shot 2016-06-21 at 1 20 39 pm](https://cloud.githubusercontent.com/assets/583202/16239464/f7772ed6-37b2-11e6-8360-1f31228ae7de.png)

**Comment by weerd** [comment]
Did you find that new one on icomoon? @DFurnes I can't locate it :\

**Comment by weerd** [comment]
Wait, just found it!
