### ISSUE TITLE
Errors on running Forge on local

### ISSUE THREAD

**Issue by samusiu** [DoSomethingArchive/forge#560]
![screen shot 2016-07-07 at 1 30 26 pm](https://cloud.githubusercontent.com/assets/19839989/16662767/03708a84-4447-11e6-917d-a9467a4ee07a.png)

**Comment by samusiu** [comment]
@DFurnes!

**Comment by DFurnes** [comment]
It looks like those two packages were published without their `dist/` folders. 😕 I'll try re-publishing them.
